/**
* @Author            : jh.jung
* @Description 		 : 
* @Target            : 
* @Modification Log
  Ver      Date            Author           Modification
  ===================================================================================
  1.0      2024-12-13      jh.jung           Created
*/

@IsTest
private class CampaignUtilityBarController_test {

    @IsTest
    static void testBehavior() {
        CampaignUtilityBarController.getCampaignList();
    }
}