/**
* @Author            : payo03@solomontech.net
* @Description 		 : 
* @Target            : 
* @Modification Log
  Ver      Date            Author                           Modification
  ===================================================================================
  1.0      2025-04-17      payo03@solomontech.net           Created
*/
public without sharing abstract class CommonAfterProcess {

    public abstract Object doAfterProcess(Object obj);
}