/**
* @Author            : payo03@solomontech.net
* @Description 		 : 동적 Trigger Handler 실행을 위한 Interface Class
* @Reference         : LGE 상담필드 TriggerHandler 참조
* @Target            :
* @Modification Log
  Ver      Date            Author                           Modification
  ===================================================================================
  1.0      2024-11-06      payo03@solomontech.net           Created
*/
public interface ITrigger {
    // Run Trigger Handler method
    void run();
}